?start: inputs
?inputs: calculation
  | inputs "&" calculation
?calculation: expression [unit "TO" unit]
?expression: product
  | expression ("+" | "-") product
?product: atom
  | product ("*" | "/") atom
?atom: SIGNED_NUMBER
  | ["round" | "floor" | "ceil"] "(" expression ")"
?unit: LWORD
  | unit LWORD
LWORD: LCASE_LETTER+
%import common.LCASE_LETTER
%import common.SIGNED_NUMBER
%import common.WS_INLINE
%ignore WS_INLINE
