?start: start SEP calculation
  | calculation
?calculation: expression conversion?
?expression: expression OP product
  | product
?product: product OPP atom
  | atom
?atom: SIGNED_NUMBER
  | FUNC closure
  | closure
  | expression
?closure: PL expression PR
?conversion: unit CONVERT unit
?unit: WUNIT+
SEP: "&"
OP: "+" | "-"
OPP: "*" | "/"
FUNC: "round" | "floor" | "ceil" | "abs"
PL: "("
PR: ")"
CONVERT: "TO"
WUNIT: /[a-z]+/
%import common.SIGNED_NUMBER
%import common.WS
%ignore WS
