?start: start SEP calculation
  | calculation
?calculation: expression conversion?
?expression: expression OP product
  | product
?product: product OPP atom
  | atom
?atom: N
  | FUNC closure
  | closure
  | expression
?closure: PL expression PR
?conversion: unit TO unit
?unit: WUNIT+
SEP: "&"
OP: "+" | "-"
OPP: "*" | "/"
FUNC: "round" | "floor" | "ceil" | "abs"
PL: "("
PR: ")"
TO: "TO"
WUNIT: /[a-z]+/
N: OP DECIMAL | SIGNED_INT
%import common.DECIMAL
%import common.SIGNED_INT
%import common.WS
%ignore WS
