?start: start "&" calculation
  | calculation
?calculation: expression conversion?
?expression: expression OP product
  | product
?product: product OPP atom
  | atom
?atom: N
  | FUNC closure
  | closure
  | expression
?closure: "(" expression ")"
?conversion: unit "TO" unit
?unit: WUNIT+
FUNC: "round" | "floor" | "ceil" | "abs"
WUNIT: LCASE_LETTER+
OPP: "*" | "/"
OP: "+" | "-"
N: OP? DECIMAL | SIGNED_INT
%import common.LCASE_LETTER
%import common.DECIMAL
%import common.SIGNED_INT
%import common.WS
%ignore WS
